DRAFT: Deltalake WIP
projectnessie/nessie-demos pull request #31
Opened 2021-05-13 10:08 UTC by snazy

2021-05-13 10:10 UTC, snazy commented
Note: the new notebook and it's test doesn't work yet, it's derfinitely still lacking a bunch of stuff

2021-05-20 16:23 UTC, snazy commented
This one is nearly ready. It currently requires a custom Nessie build with https://github.com/projectnessie/nessie/pull/1249, so as soon as that Nessie PR is merged and a corresponding Nessie version released, this PR can be finalized and merge.

2021-05-21 14:02 UTC, nastra requested changes

2021-05-21 14:02 UTC, nastra commented on colab/nessie-delta-demo-nba.ipynb
> +    "# `main` hasn't changed been changed and still has the `totals_stats` table\n",
`main` hasn't been changed and still has the `totals_stats` table

2021-05-21 14:02 UTC, nastra commented on colab/nessie-delta-demo-nba.ipynb
> +    "Notice the use of the `nessie` catalog and the use of `@experiment` to view data on the `experiment` branch"
this probably should be removed then

2021-05-21 14:02 UTC, nastra commented on colab/nessie-delta-demo-nba.ipynb
> +    "and compare to the contents of the `salaries` table on the `main` branch. Notice that we didn't have to specify `@branchName` as it defaulted\n",
same here, we're mentioning `@branchName` usage

2021-05-21 14:25 UTC, snazy commented on colab/nessie-delta-demo-nba.ipynb
> +    "spark.sql(\"select * from nessie_nba_salaries\").show()"
Delta doesn't support the `@reference` syntax at all, sad.

2021-05-21 14:30 UTC, nastra approved these changes

2021-05-21 14:44 UTC, merged